# Generated by Django 3.0.2 on 2020-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_main',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
