# Generated by Django 3.0.2 on 2020-02-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200208_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='color',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='size',
        ),
        migrations.AddField(
            model_name='colorfeature',
            name='feature',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Feature'),
        ),
        migrations.AddField(
            model_name='size',
            name='feature',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Feature'),
        ),
    ]
