# Generated by Django 3.0.2 on 2020-02-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200209_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='colorfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='colorfeature',
            name='name',
        ),
        migrations.RemoveField(
            model_name='size',
            name='feature',
        ),
        migrations.AddField(
            model_name='colorfeature',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Product'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='sizefeature',
            name='size',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Size'),
        ),
        migrations.AddField(
            model_name='colorfeature',
            name='color',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Color'),
        ),
    ]
